### ISSUE TITLE
Using this grammar for syntax highlighting on GitHub

### ISSUE THREAD

**Issue by DecimalTurn** [kimsey0/iCalendar-sublime#1]
This is just a heads up that I'm currently in the process of adding support for iCalendar on GitHub (https://github.com/github-linguist/linguist/issues/6910) and I'm considering using the grammar provided in this repo for syntax highlighting.

Let me know if this is a problem. Normally, there is nothing to change to a `.tmLanguage` file for it to be compatible with GitHub's syntax highlighting, but if there are minor changes needed, I'll let you know or make a PR.

Cheers!

**Comment by kimsey0** [comment]
That's alright with me! Feel free to contribute back any improvements to the grammar.
